const STORAGE_KEY='networkee_2_0';
const LEGACY_KEYS=['networkee_mvp_v8','networkee_mvp_v7','networkee_mvp_v6','networkee_mvp_v5','networkee_mvp_v4','networkee_mvp_v3','networkee_mvp_v2','networkee_mvp_v1'];
const uid=()=>crypto.randomUUID();
const daysAgo=n=>{const d=new Date();d.setDate(d.getDate()-n);return d.toISOString()};
const daysFromNow=n=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const seed={contacts:[{id:uid(),name:'Angela Arena',role:'Assistentin der Geschäftsleitung',company:'',tags:['Organisation','Smart Reminders'],goal:'Kontakt warm halten',priority:'Medium',birthday:'',memory:'Mag klare Strukturen und arbeitet nah an der Geschäftsleitung. Offen für smarte Erinnerungen und vorbereitende Gesprächsnotizen.',city:'Fehraltorf',region:'Zürich',country:'Schweiz',createdAt:daysAgo(42)},{id:uid(),name:'Peter Streiff',role:'Sales Professional',company:'',tags:['Sales','CRM','Padel'],goal:'Geschäftschance entwickeln',priority:'High',birthday:'',memory:'Vertrieb und CRM sind zentrale Themen. Persönliche Vorbereitung vor Gesprächen ist ihm wichtig. Interessiert sich für den Sales-Use-Case von Networkee.',city:'Bassersdorf',region:'Zürich',country:'Schweiz',createdAt:daysAgo(120)}],notes:[]};
seed.notes=[{id:uid(),contactId:seed.contacts[0].id,type:'Meeting',text:'Über Organisation, persönliche Kontaktpflege und Reminder gesprochen. Angela sieht Nutzen in vorbereitenden Gesprächsnotizen.',nextStep:'Feedback zum MVP einholen.',followupDate:daysFromNow(7),createdAt:daysAgo(18)},{id:uid(),contactId:seed.contacts[1].id,type:'Call',text:'Peter betonte, dass vor Gesprächen letzte Themen, offene Chancen und persönliche Details zählen.',nextStep:'Sales-Use-Case schicken und Feedback einholen.',followupDate:daysFromNow(-1),createdAt:daysAgo(91)}];
let state=loadState(),peopleFilter='all';
function normalize(d){return{contacts:(d.contacts||[]).map(c=>({role:'',company:'',tags:[],goal:'Kontakt warm halten',priority:'Medium',birthday:'',memory:'',city:'',region:'',country:'',createdAt:new Date().toISOString(),...c})),notes:d.notes||[]}}
function loadState(){const own=localStorage.getItem(STORAGE_KEY);if(own)try{return normalize(JSON.parse(own))}catch{}for(const k of LEGACY_KEYS){const raw=localStorage.getItem(k);if(raw)try{const migrated=normalize(JSON.parse(raw));localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));return migrated}catch{}}return structuredClone(seed)}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll()}
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=n=>String(n||'?').split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const notesFor=id=>state.notes.filter(n=>n.contactId===id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
const lastNote=c=>notesFor(c.id)[0]||null;
function daysSince(s){if(!s)return Infinity;return Math.max(0,Math.floor((new Date()-new Date(s))/86400000))}
function age(c){return daysSince(lastNote(c)?.createdAt||c.createdAt)}
function attention(c){const d=age(c);const overdue=notesFor(c.id).some(n=>n.followupDate&&n.followupDate<=new Date().toISOString().slice(0,10));return overdue||(c.priority==='High'&&d>60)||d>120}
function relState(c){const d=age(c);if(attention(c))return{label:'Needs attention',cls:'attention'};if(d<=30)return{label:'Active',cls:''};return{label:'Quiet',cls:''}}
function actionFor(c){const overdue=notesFor(c.id).find(n=>n.followupDate&&n.followupDate<=new Date().toISOString().slice(0,10));if(overdue)return overdue.nextStep||'Follow-up aufnehmen';const last=lastNote(c);if(last?.nextStep)return last.nextStep;if(age(c)>120)return 'Entscheide, ob du die Beziehung wieder aktivieren möchtest.';if(age(c)>60)return 'Mit einem persönlichen Check-in an das letzte Thema anknüpfen.';return 'Kein dringender Schritt – Beziehung natürlich weiterführen.'}
function navTo(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));closeMenu();window.scrollTo({top:0,behavior:'smooth'})}
function openMenu(){sideMenu.classList.add('open');sideMenu.setAttribute('aria-hidden','false')}function closeMenu(){sideMenu.classList.remove('open');sideMenu.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>navTo(b.dataset.nav)));menuBtn.onclick=openMenu;closeMenuBtn.onclick=closeMenu;sideMenu.onclick=e=>{if(e.target===sideMenu)closeMenu()};
function renderToday(){const now=new Date(),h=now.getHours();greeting.textContent=h<12?'Guten Morgen.':h<18?'Guten Tag.':'Guten Abend.';todayDate.textContent=new Intl.DateTimeFormat('de-CH',{weekday:'long',day:'numeric',month:'long'}).format(now).toUpperCase();const due=state.notes.filter(n=>n.followupDate&&n.followupDate<=now.toISOString().slice(0,10));const needs=state.contacts.filter(attention).sort((a,b)=>age(b)-age(a));const actions=[];due.forEach(n=>{const c=state.contacts.find(x=>x.id===n.contactId);if(c)actions.push({c,reason:'Follow-up fällig',text:n.nextStep||'Kontakt aufnehmen'})});needs.forEach(c=>{if(!actions.some(a=>a.c.id===c.id))actions.push({c,reason:`${age(c)} Tage seit letztem Moment`,text:actionFor(c)})});const top=actions[0];briefCard.innerHTML=top?`<div><p class="kicker">NETWORKee BRIEF</p><h2>${esc(top.c.name)} verdient heute deine Aufmerksamkeit.</h2><p>${esc(top.text)}</p></div><button onclick="openProfile('${top.c.id}')">Kontext ansehen →</button>`:`<div><p class="kicker">NETWORKee BRIEF</p><h2>Dein Netzwerk ist heute ruhig.</h2><p>Keine dringenden Follow-ups. Ein guter Moment, um einen neuen gemeinsamen Moment festzuhalten.</p></div><button data-capture>Moment erfassen →</button>`;briefCard.querySelector('[data-capture]')?.addEventListener('click',()=>navTo('capture'));actionCount.textContent=actions.length;todayActions.innerHTML=actions.length?actions.slice(0,3).map(a=>`<article class="action-card" onclick="openProfile('${a.c.id}')"><div class="avatar">${initials(a.c.name)}</div><div><h3>${esc(a.c.name)}</h3><p>${esc(a.text)}</p><div class="why">${esc(a.reason)}</div></div><button class="arrow">→</button></article>`).join(''):`<div class="empty-card">Heute ist nichts dringend. Beziehungen brauchen nicht jeden Tag eine Aufgabe.</div>`;const birthdays=state.contacts.filter(c=>birthdayWithin(c,30)).slice(0,2);const upcoming=state.notes.filter(n=>n.followupDate&&n.followupDate>now.toISOString().slice(0,10)).sort((a,b)=>a.followupDate.localeCompare(b.followupDate)).slice(0,2);const cards=[...birthdays.map(c=>({i:'✦',t:c.name,p:`Geburtstag ${birthdayWithin(c,30)===0?'heute':`in ${birthdayWithin(c,30)} Tagen`}`})),...upcoming.map(n=>({i:'↗',t:state.contacts.find(c=>c.id===n.contactId)?.name||'Follow-up',p:`${formatDate(n.followupDate)} · ${n.nextStep||'Kontakt aufnehmen'}`}))].slice(0,4);comingUp.innerHTML=cards.length?cards.map(x=>`<article class="coming-card"><span>${x.i}</span><h3>${esc(x.t)}</h3><p>${esc(x.p)}</p></article>`).join(''):`<div class="empty-card">Noch keine kommenden Anlässe oder Follow-ups.</div>`}
function birthdayWithin(c,n){if(!c.birthday)return null;const now=new Date();const[,m,d]=c.birthday.split('-').map(Number);let x=new Date(now.getFullYear(),m-1,d);if(x<new Date(now.toDateString()))x.setFullYear(now.getFullYear()+1);const diff=Math.ceil((x-now)/86400000);return diff<=n?diff:null}
function renderPeople(){const q=searchInput.value.toLowerCase();let arr=state.contacts.filter(c=>[c.name,c.role,c.company,c.city,c.country,c.memory,...(c.tags||[])].join(' ').toLowerCase().includes(q));if(peopleFilter==='attention')arr=arr.filter(attention);if(peopleFilter==='work')arr=arr.filter(c=>!String(c.goal).toLowerCase().includes('privat'));if(peopleFilter==='close')arr=arr.filter(c=>c.priority==='High'&&!attention(c));arr.sort((a,b)=>Number(attention(b))-Number(attention(a))||a.name.localeCompare(b.name));contactList.innerHTML=arr.length?arr.map(c=>{const r=relState(c),n=lastNote(c);return`<article class="person-row" onclick="openProfile('${c.id}')"><div class="person-top"><div class="avatar">${initials(c.name)}</div><div><h3>${esc(c.name)}</h3><p class="meta">${esc([c.role,c.company,c.city].filter(Boolean).join(' · ')||c.goal)}</p></div><span class="state-dot ${r.cls}" title="${r.label}"></span></div><div class="person-context">${(c.tags||[]).slice(0,3).map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div><p class="person-memory">${esc(n?.text||c.memory||'Noch keine gemeinsame Erinnerung festgehalten.')}</p><div class="person-foot"><span>${age(c)===Infinity?'Noch kein Moment':`${age(c)} Tage seit letztem Moment`}</span><span>${esc(r.label)}</span></div></article>`}).join(''):`<div class="empty-card">Keine Personen gefunden.</div>`}
searchInput.oninput=renderPeople;peopleFilters.onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;peopleFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderPeople()};
function renderNoteContacts(){noteContact.innerHTML=state.contacts.length?state.contacts.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join(''):'<option value="">Zuerst Person hinzufügen</option>'}
function setCapture(type,placeholder){noteType.value=type;noteText.value='';noteText.placeholder=placeholder;noteText.focus()}voiceNoteBtn.onclick=()=>setCapture('Voice Note','Sprich bzw. notiere frei: Was war wichtig? Was möchtest du später noch wissen?');textNoteBtn.onclick=()=>setCapture('Nachricht','Was ist passiert? Welche Details möchtest du erinnern?');meetingNoteBtn.onclick=()=>setCapture('Meeting','Was wurde besprochen? Entscheidungen, persönliche Themen, nächster Schritt …');
noteForm.onsubmit=e=>{e.preventDefault();if(!noteContact.value)return;state.notes.unshift({id:uid(),contactId:noteContact.value,type:noteType.value,text:noteText.value.trim(),nextStep:nextStep.value.trim(),followupDate:followupDate.value,createdAt:new Date().toISOString()});e.target.reset();save();navTo('today')};
function renderInsights(){const active=state.contacts.filter(c=>age(c)<=60).length,needs=state.contacts.filter(attention).length,follow=state.notes.filter(n=>n.followupDate&&n.followupDate>=new Date().toISOString().slice(0,10)).length;networkHealth.innerHTML=`<p class="kicker">NETWORK HEALTH</p><h2>${state.contacts.length?`${active} Beziehungen sind aktiv.`:'Dein Netzwerk entsteht.'}</h2><p>${needs?`${needs} ${needs===1?'Beziehung verdient':'Beziehungen verdienen'} aktuell Aufmerksamkeit.`:'Aktuell gibt es keine kritischen Signale.'}</p><div class="health-stats"><div><strong>${active}</strong><span>aktiv</span></div><div><strong>${needs}</strong><span>Aufmerksamkeit</span></div><div><strong>${follow}</strong><span>Follow-ups</span></div></div>`;const noMemory=state.contacts.filter(c=>!c.memory?.trim()).length;const staleHigh=state.contacts.filter(c=>c.priority==='High'&&age(c)>60).length;const tagCounts={};state.contacts.forEach(c=>(c.tags||[]).forEach(t=>tagCounts[t]=(tagCounts[t]||0)+1));const topTag=Object.entries(tagCounts).sort((a,b)=>b[1]-a[1])[0];const insights=[];if(staleHigh)insights.push({i:'!',h:`${staleHigh} wichtige ${staleHigh===1?'Beziehung braucht':'Beziehungen brauchen'} Aufmerksamkeit`,p:'Hohe Relevanz und längere Ruhephase treffen hier zusammen.'});if(noMemory)insights.push({i:'✦',h:`Bei ${noMemory} ${noMemory===1?'Person fehlt':'Personen fehlen'} persönlicher Kontext`,p:'Ein paar echte Erinnerungen machen Networkee später deutlich hilfreicher.'});if(topTag)insights.push({i:'◎',h:`${topTag[0]} ist ein starker Cluster`,p:`${topTag[1]} Personen in deinem Netzwerk teilen dieses Thema.`});if(!insights.length)insights.push({i:'✓',h:'Dein Netzwerk ist gut dokumentiert',p:'Mit mehr gemeinsamen Momenten werden die Muster mit der Zeit aussagekräftiger.'});insightList.innerHTML=insights.map(x=>`<article class="insight-card"><div class="icon">${x.i}</div><h3>${esc(x.h)}</h3><p>${esc(x.p)}</p></article>`).join('');const countries={};state.contacts.forEach(c=>{if(c.country)countries[c.country]=(countries[c.country]||0)+1});const top=Object.entries(countries).sort((a,b)=>b[1]-a[1]);geoPreview.innerHTML=`<p class="kicker">NETWORK GEOGRAPHY</p><h3>${top.length?`${top.length} ${top.length===1?'Land':'Länder'} in deinem Netzwerk`:'Standorte noch nicht vollständig'}</h3><p>${top.length?top.slice(0,3).map(([c,n])=>`${c} · ${n}`).join(' &nbsp; '):'Wohnort und Land bleiben im Datenmodell. Eine echte Karte kommt mit Backend und professionellem Geocoding.'}</p>`}
function openContactDialog(c=null){dialogTitle.textContent=c?'Person bearbeiten':'Person hinzufügen';contactId.value=c?.id||'';contactName.value=c?.name||'';contactRole.value=c?.role||'';contactCompany.value=c?.company||'';contactCity.value=c?.city||'';contactRegion.value=c?.region||'';contactCountry.value=c?.country||'';relationshipGoal.value=c?.goal||'Kontakt warm halten';contactPriority.value=c?.priority||'Medium';contactBirthday.value=c?.birthday||'';contactTags.value=(c?.tags||[]).join(', ');contactMemory.value=c?.memory||'';contactDialog.showModal()}
addContactBtn.onclick=()=>openContactDialog();cancelDialog.onclick=()=>contactDialog.close();contactForm.onsubmit=e=>{e.preventDefault();const id=contactId.value||uid(),old=state.contacts.find(c=>c.id===id);const c={id,name:contactName.value.trim(),role:contactRole.value.trim(),company:contactCompany.value.trim(),city:contactCity.value.trim(),region:contactRegion.value.trim(),country:contactCountry.value.trim(),goal:relationshipGoal.value,priority:contactPriority.value,birthday:contactBirthday.value,tags:contactTags.value.split(',').map(x=>x.trim()).filter(Boolean),memory:contactMemory.value.trim(),createdAt:old?.createdAt||new Date().toISOString()};const i=state.contacts.findIndex(x=>x.id===id);i>=0?state.contacts[i]=c:state.contacts.unshift(c);contactDialog.close();save()};
function openProfile(id){const c=state.contacts.find(x=>x.id===id);if(!c)return;const notes=notesFor(id),r=relState(c),about=c.memory||`${c.name} ist Teil deines ${String(c.goal).toLowerCase()}-Kontexts. Mit jedem erfassten Moment wird dieses Profil persönlicher.`;profileContent.innerHTML=`<div class="profile-hero"><div class="avatar">${initials(c.name)}</div><div><h2>${esc(c.name)}</h2><p>${esc([c.role,c.company,c.city,c.country].filter(Boolean).join(' · '))}</p></div><span class="state-dot ${r.cls}"></span></div><section class="profile-section"><h3>About</h3><p class="about-copy">${esc(about)}</p></section><section class="profile-section"><h3>Remember</h3><div class="memory-chips">${[...(c.tags||[]),c.goal].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('')||'<span>Noch keine Themen</span>'}</div></section><section class="profile-section"><h3>Next</h3><div class="next-card"><strong>${esc(actionFor(c))}</strong><p>${age(c)===Infinity?'Noch kein gemeinsamer Moment dokumentiert.':`Letzter dokumentierter Moment vor ${age(c)} Tagen.`}</p></div></section><section class="profile-section"><h3>Your history</h3><div class="timeline">${notes.length?notes.map(n=>`<article class="timeline-item"><span class="timeline-dot"></span><div><h4>${formatDate(n.createdAt)} · ${esc(n.type)}</h4><p>${esc(n.text)}</p></div></article>`).join(''):'<div class="empty-card">Noch keine gemeinsamen Momente dokumentiert.</div>'}</div></section><div class="profile-actions"><button class="primary" onclick="quickNote('${c.id}')">Moment erfassen</button><button class="secondary" onclick="editContact('${c.id}')">Bearbeiten</button></div>`;profileDialog.showModal()}
closeProfile.onclick=()=>profileDialog.close();window.openProfile=openProfile;window.editContact=id=>{profileDialog.close();openContactDialog(state.contacts.find(c=>c.id===id))};window.quickNote=id=>{profileDialog.close();navTo('capture');noteContact.value=id;noteText.focus()};
function formatDate(s){return new Intl.DateTimeFormat('de-CH',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s))}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
exportBtn.onclick=()=>{closeMenu();exportDialog.showModal()};closeExport.onclick=()=>exportDialog.close();exportJsonBtn.onclick=()=>download('networkee-backup.json',JSON.stringify(state,null,2),'application/json');exportCsvBtn.onclick=()=>{const rows=[['Name','Role','Company','City','Region','Country','Goal','Priority','Tags','Memory'],...state.contacts.map(c=>[c.name,c.role,c.company,c.city,c.region,c.country,c.goal,c.priority,(c.tags||[]).join('|'),c.memory])];download('networkee-contacts.csv',rows.map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')};exportVcardBtn.onclick=()=>download('networkee-contacts.vcf',state.contacts.map(c=>`BEGIN:VCARD\nVERSION:3.0\nFN:${c.name}\nORG:${c.company||''}\nTITLE:${c.role||''}\nADR:;;${c.city||''};${c.region||''};;${c.country||''}\nNOTE:${(c.memory||'').replace(/\n/g,' ')}\nEND:VCARD`).join('\n'),'text/vcard');
resetDemoBtn.onclick=()=>{if(confirm('Demo-Daten zurücksetzen?')){state=structuredClone(seed);save();navTo('today')}};clearDataBtn.onclick=()=>{if(confirm('Alle lokalen Networkee-Daten löschen?')){state={contacts:[],notes:[]};save();navTo('today')}};
function renderAll(){renderToday();renderPeople();renderNoteContacts();renderInsights()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=20').catch(()=>{});renderAll();